name: Linux

on:
 push:
   branches: [master]
 pull_request:
   branches: [master]

jobs:
 build-bin:
   runs-on: "ubuntu-latest"
   steps:
     - uses: actions/checkout@v2
     - name: Pull Linux Bevy Dependencies
       run: |
        sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
     - name: Prepare Toolchain
       run: rustup show
     - name: Build
       run: cargo build --verbose
     - name: Run Tests
       run: cargo test --verbose